services:
  - type: web
    name: koperasi-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn koperasi_api.wsgi --log-file - --workers 4 --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4