# Generated by Django 5.2.3 on 2025-07-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Simpanan')),
                ('deposit_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Simpanan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='members.member', verbose_name='Anggota')),
            ],
            options={
                'verbose_name': 'Simpanan',
                'verbose_name_plural': 'Simpanan',
                'ordering': ['-deposit_date'],
            },
        ),
    ]
