# Generated by Django 5.2.3 on 2025-07-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Simpanan')),
                ('deposit_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Simpanan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Simpanan',
                'verbose_name_plural': 'Simpanan',
                'ordering': ['-deposit_date'],
            },
        ),
    ]
