# Generated by Django 5.2.3 on 2025-07-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Pinjaman')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tingkat Bunga (%)')),
                ('term_months', models.IntegerField(verbose_name='Jangka Waktu (Bulan)')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('paid', 'Lunas')], default='pending', max_length=10, verbose_name='Status')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member', verbose_name='Anggota')),
            ],
            options={
                'verbose_name': 'Pinjaman',
                'verbose_name_plural': 'Pinjaman',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Dibayar')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pembayaran')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan', verbose_name='Pinjaman')),
            ],
            options={
                'verbose_name': 'Pembayaran Pinjaman',
                'verbose_name_plural': 'Pembayaran Pinjaman',
                'ordering': ['-payment_date'],
            },
        ),
    ]
