# Generated by Django 5.2.3 on 2025-07-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member', verbose_name='Anggota'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan', verbose_name='Pinjaman'),
        ),
    ]
