# Generated by Django 5.2.3 on 2025-07-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Anggota')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor Telepon')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Anggota',
                'ordering': ['name'],
            },
        ),
    ]
