# Generated by Django 5.2.3 on 2025-07-15 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255, verbose_name='Nama Anggota')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor Telepon')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Anggota',
                'ordering': ['name'],
            },
        ),
    ]
