# Generated by Django 5.2.3 on 2025-07-13 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Anggota')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor Telepon')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Tanggal Bergabung')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Anggota',
                'ordering': ['name'],
            },
        ),
    ]
